# Generated by Django 2.0.7 on 2018-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_friend_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='follower',
            field=models.ManyToManyField(null=True, related_name='follower', to='insta.UserProfile'),
        ),
    ]
