# Generated by Django 2.0.7 on 2018-08-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_yaarbelli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaarbelli',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to='insta.UserProfile'),
        ),
        migrations.AlterField(
            model_name='yaarbelli',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to='insta.UserProfile'),
        ),
    ]
