# Generated by Django 2.0.7 on 2018-08-20 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180819_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaarbelli',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yaarbelli',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to=settings.AUTH_USER_MODEL),
        ),
    ]
